---
- name: Configure Windows VM
  hosts: windows
  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present

    - name: Copy configuration files
      win_copy:
        src: ./path/to/config_file.conf
        dest: C:\path\to\destination\config_file.conf

    - name: Install software
      win_package:
        path: C:\path\to\software_installer.exe
        state: present